# Repo: MySpace/TemplateRepo
# File: azure-pipeline.yml

name: cicd_ci

trigger:
  branches:
    include:
      - main

stages:
- stage: Test
  jobs:
  - job:
    displayName: FirstJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        mkdir mybuild
        echo rohit > mybuild/hello.txt
        echo "jain"
