name: cicd_ci
stages:
  - build
  - test
web app dev job1 build:
  stage: build
  script:
    - mkdir mybuild
    - echo rohit > mybuild/hello.txt
    - echo "other" > my.txt
    - echo "my build job"
  artifacts:
    path:
      - mybuild/
web app dev job2 test:
  stage: test
  script:
    - grep rohit mybuild/hello.txt
    - echo "my test job"
